name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Install sqlite
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-0 libsqlite3-dev
      - name: Install rust (needed for blake-py)
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain nightly
      - name: Get mythril signature db
        run: |
          cd /home/runner
          mkdir .mythril
          cd .mythril
          wget -O signatures.db https://github.com/ConsenSys/mythril/blob/develop/mythril/support/assets/signatures.db?raw=true
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
